artifacts_root: artifacts

data_ingestion:
  token_URL: https://auth.greenyellow.com/realms/gy-prod/protocol/openid-connect/token


data_availability:
  root_dir: artifacts/data_availability


anomaly_occurrence:
  root_dir: artifacts/anomaly_occurrence

  